# This configuration was influenced by googletest:
# https://github.com/google/googletest/blob/master/appveyor.yml

environment:
  matrix:
    - ARCH: x86
      GENERATOR: Visual Studio 14 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - ARCH: x86_64
      GENERATOR: Visual Studio 14 2015 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - ARCH: x86
      GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - ARCH: x86_64
      GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

configuration:
  - Debug
  - Release

# Unclear how to do this in PowerShell.
install:
  - ps: |
      $env:PATH = "$env:PYTHON;$env:PYTHON\Scripts;$env:PATH"
      $ErrorActionPreference = "Stop"
      pip.exe install --upgrade pip
      pip.exe install --upgrade conan --ignore-installed
      conan user
      conan --version
      conan remote add jfreeman https://api.bintray.com/conan/jfreeman/jfreeman
      conan remote list

build_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      $env:CMAKE_BUILD_PARALLEL_LEVEL = ""
      md build
      cd build
      conan install `
        --setting "arch=$env:ARCH" `
        --setting "build_type=$env:CONFIGURATION" `
        ..
      cmake `
        -G "$env:GENERATOR" `
        "-DCMAKE_CONFIGURATION_TYPES=$env:CONFIGURATION" `
        ..
      cmake --build . --config "$env:CONFIGURATION"

test_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      $env:CTEST_PARALLEL_LEVEL = ""
      ctest --build-config "$env:CONFIGURATION" --verbose
