# This configuration was influenced by googletest:
# https://github.com/google/googletest/blob/master/appveyor.yml

environment:
  matrix:
    - ARCH: x86
      GENERATOR: Visual Studio 14 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - ARCH: x86_64
      GENERATOR: Visual Studio 14 2015 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - ARCH: x86
      GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - ARCH: x86_64
      GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

configuration:
  - Debug
  - Release

# Unclear how to do this in PowerShell.
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - ps: |
      $ErrorActionPreference = "Stop"
      pip.exe --disable-pip-version-check install conan
      Invoke-RestMethod https://raw.githubusercontent.com/thejohnfreeman/cmake-future/master/install.ps `
        | powershell
      conan user
      conan --version
      conan remote add jfreeman https://api.bintray.com/conan/jfreeman/jfreeman
      conan remote list

# `/m` is for parallel build.
build_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      md build
      cd build
      conan install `
        --setting "arch=$env:ARCH" `
        --setting "build_type=$env:CONFIGURATION" `
        ..
      cmake `
        -G "$env:GENERATOR" `
        "-DCMAKE_CONFIGURATION_TYPES=Debug;Release" `
        ..
      cmake --build . --config "$env:CONFIGURATION" -- /m

test_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      ctest -C "$env:CONFIGURATION" -V
