# This configuration was influenced by googletest:
# https://github.com/google/googletest/blob/master/appveyor.yml

environment:
  matrix:
    - GENERATOR: Visual Studio 14 2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - GENERATOR: Visual Studio 14 2015 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - GENERATOR: Visual Studio 15 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GENERATOR: Visual Studio 15 2017 Win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

configuration:
  - Debug
  - Release

build_script:
  - ps: |
      md build
      conan install .
      cd build
      cmake -G $env:GENERATOR "-DCMAKE_CONFIGURATION_TYPES=Debug;Release" ..
      if ($LastExitCode -ne 0) {
        throw $ErrorMessage
      }
      cmake --build . --config $env:CONFIGURATION -- /m
      if ($LastExitCode -ne 0) {
        throw $ErrorMessage
      }

test_script:
  - ps: |
      ctest -C $env:CONFIGURATION -V
      if ($LastExitCode -ne 0) {
        throw $ErrorMessage
      }
