os:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake ..

build:
  parallel: true
  project: build\autocheck.sln

test_script:
  - ctest -C %CONFIGURATION% -V
