sudo: required
language: cpp

matrix:
  include:
    # We need to use Ubuntu Xenial to upgrade pip.
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
    # GCC on OSX is just a wrapper for Clang.

install:
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade conan --ignore-installed
  - conan user
  - conan --version

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j 4
  - ctest -V
