sudo: required
language: cpp

matrix:
  include:
    # We need use to Ubuntu Trusty to get pip3.
    - os: linux
      dist: trusty
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: linux
      dist: trusty
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Release

install:
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade conan
  - conan user
  - conan --version

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j 4
  - ctest -V
