sudo: required
language: cpp

matrix:
  include:
    # We need to use Ubuntu Xenial to upgrade pip.
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
    # GCC on OSX is just a wrapper for Clang.

install:
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade conan --ignore-installed
  - conan user
  - conan --version
  - conan remote list

script:
  - mkdir build
  - cd build
  - conan install \
    --setting "compiler=$COMPILER" \
    --setting "compiler.libcxx=libstdc++11" \
    --setting "build_type=$BUILD_TYPE" \
    --build missing \
    ..
  - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1' \
    cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build . --config ${BUILD_TYPE} -- -j 4
  - ctest -C $BUILD_TYPE -V
