language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: linux
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Release

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
  - ctest -V
