language: cpp

addons:
  apt:
    packages:
      - python3
      - python3-pip

matrix:
  include:
    # We need use to Ubuntu Trusty to get pip3.
    - os: linux
      dist: trusty
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: linux
      dist: trusty
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Release

install:
  - pip3 install canon --user
  - export PATH=$HOME/.local/bin:$PATH
  - conan user
  - conan --version

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j 4
  - ctest -V
