language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: linux
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: linux
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
    - os: osx
      compiler: gcc
      env:
        - BUILD_TYPE=Release

install:
  - sudo pip install canon
  - python -c 'import sys; print(sys.path)'
  - conan user
  - conan --version

script:
  - mkdir build
  - cd build
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j 4
  - ctest -V
