sudo: required
language: cpp

.xenial: &xenial
  os: linux
  dist: xenial
  addons:
    apt:
      sources:
        - deadsnakes
      packages:
        - python3.6-dev
  before_install:
    - curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6

matrix:
  include:
    # We need to use Ubuntu Xenial to upgrade pip.
    - <<: *xenial
      compiler: clang
      env:
        - BUILD_TYPE=Debug
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - <<: *xenial
      compiler: clang
      env:
        - BUILD_TYPE=Release
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - <<: *xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Debug
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - <<: *xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Release
        - CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=1'
        - LIBCXX=libstdc++11
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Debug
        - LIBCXX=libc++
    - os: osx
      compiler: clang
      env:
        - BUILD_TYPE=Release
        - LIBCXX=libc++
    # GCC on OSX is just a wrapper for Clang.

install:
  # The root environment on Travis does not have cmake on its PATH.
  # https://github.com/travis-ci/travis-ci/issues/9113#issuecomment-366448032
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade conan --ignore-installed
  - conan user
  - conan --version
  - conan remote add jfreeman https://api.bintray.com/conan/jfreeman/jfreeman
  - conan remote list

script:
  - mkdir build
  - cd build
  - export CMAKE_BUILD_PARALLEL_LEVEL=
  - conan install
    --setting "compiler.libcxx=$LIBCXX"
    --setting "build_type=$BUILD_TYPE"
    --build missing
    ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - cmake --build . --config ${BUILD_TYPE}
  - export CTEST_PARALLEL_LEVEL=
  - ctest --build-config $BUILD_TYPE --verbose
